apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redhatai-meta-llama-31-70b-instruct-quantized-w4a16
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 80Gi
  storageClassName: gp3-csi