apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: llama-3-1-8b-instruct
  namespace: rhaiis-namespace
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: gp3-csi