apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qwen2-5-0-5b
  namespace: rhaiis-namespace
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: gp3-csi