apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: llama-3-2-3b-instruct-q8
  namespace: rhaiis-namespace
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: gp3-csi